LogFile /var/log/clamav/clamd.log
LogFileMaxSize 10M
LogTime yes
LogRotate yes
PidFile /run/clamav/clamd.pid
DatabaseDirectory /var/lib/clamav
TemporaryDirectory /tmp
LocalSocket /tmp/clamd.sock
FixStaleSocket yes
TCPSocket 3310
TCPAddr 0.0.0.0
User clamav

StreamMaxLength 40M
MaxFileSize 40M
MaxScanSize 96M
MaxScanTime 25000
MaxRecursion 16
MaxFiles 5000
MaxThreads 2
MaxQueue 4
AlertExceedsMax yes
AlertEncrypted yes
