import { useMemo, useState, type FormEvent } from "react";
import { Copy, Plus, Search, ShieldCheck, UserRoundCheck, UserRoundX } from "lucide-react";
import type { TutorSummary } from "../../../shared/types";
import { api, type CreateTutorResult } from "../../api";
import { Button, EmptyState, ErrorState, FormField, IconButton, LoadingBlock, Modal, Notice, PageHeader, StatusBadge, formatDateTime, initials, useAsyncData } from "../../components/UI";

function tutorInviteLink(result: CreateTutorResult) {
  return result.inviteUrl ? new URL(result.inviteUrl, window.location.origin).toString() : "";
}

export function TutorsPage() {
  const resource = useAsyncData(() => api.tutors.list(), []);
  const [search, setSearch] = useState("");
  const [createOpen, setCreateOpen] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);
  const [actionId, setActionId] = useState<string | null>(null);
  const filtered = useMemo(() => { const query = search.trim().toLocaleLowerCase("ru"); return (resource.data ?? []).filter((tutor) => !query || `${tutor.displayName} ${tutor.loginName}`.toLocaleLowerCase("ru").includes(query)); }, [resource.data, search]);
  const toggleStatus = async (tutor: TutorSummary) => { setActionId(tutor.id); setActionError(null); try { await api.tutors.setStatus(tutor.id, tutor.status === "suspended" ? "active" : "suspended"); resource.reload(); } catch (reason) { setActionError(reason instanceof Error ? reason.message : "Не удалось изменить статус"); } finally { setActionId(null); } };
  return <div className="page"><PageHeader title="Репетиторы" description="Доступ сотрудников и их ученики" actions={<Button icon={<Plus size={18} />} onClick={() => setCreateOpen(true)}>Создать аккаунт</Button>} /><div className="admin-summary"><div><span className="admin-summary__icon"><ShieldCheck size={20} /></span><span>Всего репетиторов</span><strong>{resource.data?.length ?? 0}</strong></div><div><span className="admin-summary__icon admin-summary__icon--green"><UserRoundCheck size={20} /></span><span>Активны</span><strong>{resource.data?.filter((tutor) => tutor.status === "active").length ?? 0}</strong></div><div><span className="admin-summary__icon admin-summary__icon--gray"><UserRoundX size={20} /></span><span>Ожидают входа</span><strong>{resource.data?.filter((tutor) => tutor.status === "pending").length ?? 0}</strong></div></div><div className="toolbar"><label className="search-field"><Search size={18} /><span className="sr-only">Поиск репетиторов</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Имя или логин" /></label></div>{actionError && <Notice type="error">{actionError}</Notice>}{resource.loading && <LoadingBlock label="Загружаем репетиторов" />}{resource.error && <ErrorState message={resource.error} onRetry={resource.reload} />}{resource.data && !filtered.length && <EmptyState title="Репетиторов пока нет" action={<Button variant="secondary" onClick={() => setCreateOpen(true)}>Создать аккаунт</Button>} />}{filtered.length > 0 && <div className="table-wrap"><table className="data-table"><thead><tr><th>Репетитор</th><th>Статус</th><th>Ученики</th><th>Последний вход</th><th>Создан</th><th><span className="sr-only">Действия</span></th></tr></thead><tbody>{filtered.map((tutor) => <tr key={tutor.id}><td data-label="Репетитор"><span className="person-cell"><span className="avatar avatar--small">{initials(tutor.displayName)}</span><span><strong>{tutor.displayName}</strong><small>{tutor.loginName}</small></span></span></td><td data-label="Статус"><StatusBadge status={tutor.status} /></td><td data-label="Ученики">{tutor.studentCount}</td><td data-label="Последний вход">{formatDateTime(tutor.lastLoginAt)}</td><td data-label="Создан">{formatDateTime(tutor.createdAt, { day: "numeric", month: "short", year: "numeric" })}</td><td className="table-actions"><Button variant="ghost" size="small" disabled={actionId === tutor.id || tutor.status === "pending"} onClick={() => void toggleStatus(tutor)}>{tutor.status === "suspended" ? "Включить" : "Приостановить"}</Button></td></tr>)}</tbody></table></div>}<CreateTutorModal open={createOpen} onClose={() => setCreateOpen(false)} onCreated={resource.reload} /></div>;
}

function CreateTutorModal({ open, onClose, onCreated }: { open: boolean; onClose: () => void; onCreated: () => void }) {
  const [displayName, setDisplayName] = useState(""); const [loginName, setLoginName] = useState(""); const [result, setResult] = useState<CreateTutorResult | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const close = () => { setDisplayName(""); setLoginName(""); setResult(null); setError(null); onClose(); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(null); try { setResult(await api.tutors.create({ displayName: displayName.trim(), loginName: loginName.trim() })); onCreated(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось создать репетитора"); } finally { setLoading(false); } };
  const link = result ? tutorInviteLink(result) : "";
  return <Modal open={open} title={result ? "Репетитор создан" : "Новый репетитор"} description={result ? "Передайте сотруднику одноразовую ссылку." : "Аккаунт станет активным после настройки доступа."} onClose={close}>{result ? <div className="form-stack"><div className="invite-result"><span className="avatar">{initials(result.tutor.displayName)}</span><div><strong>{result.tutor.displayName}</strong><span>{result.tutor.loginName}</span></div></div>{link && <FormField label="Пригласительная ссылка"><div className="copy-field"><input value={link} readOnly /><IconButton label="Скопировать" onClick={() => void navigator.clipboard.writeText(link)}><Copy size={18} /></IconButton></div></FormField>}<div className="modal-actions"><Button onClick={close}>Готово</Button></div></div> : <form className="form-stack" onSubmit={submit}><FormField label="Имя"><input value={displayName} onChange={(event) => setDisplayName(event.target.value)} required autoFocus /></FormField><FormField label="Логин"><input value={loginName} onChange={(event) => setLoginName(event.target.value)} required autoComplete="off" /></FormField>{error && <Notice type="error">{error}</Notice>}<div className="modal-actions"><Button type="button" variant="secondary" onClick={close}>Отмена</Button><Button type="submit" disabled={loading || !displayName.trim() || !loginName.trim()}>{loading ? "Создаём…" : "Создать"}</Button></div></form>}</Modal>;
}
